rtsp_url_cam=qazxsw
database=qazx
database_bw=
localsite=asdd
detected_img=
log_data=wwwd
main_display_img=
log_unimg=
startimgpath=
font_2fr=
font_3fr=
font_fr=
xml_file=eefv
detector_name=
detector_name_train=
pkl_file=
in_port=
in_ip=
out_port=
out_ip=
in_screen_name=
out_screen_name=
email_sub="In-time Report"
email_body="Hello $ename! Your face is successfully recognized by EZ Witness Face Recognition System at $inTime on $todayDate"
from_name="EZWitness"